FROM tiangolo/uvicorn-gunicorn-fastapi:python3.9-slim

WORKDIR /server

COPY ./server ./app

RUN pip install --no-cache-dir --upgrade -r ./app/requirements.txt

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8008"]